### ISSUE TITLE
error

### ISSUE THREAD

**Issue by akdenme** [annapogorelova/ng2-go-top-button#2]
![capture](https://cloud.githubusercontent.com/assets/28615783/25935097/e481aa18-3653-11e7-952f-94ccfd39890d.JPG)

got error like this..

**Comment by annapogorelova** [comment]
Fixed it in the latest release (**v.2.0.6**). I've also updated README with the proper instructions for SystemJS config.

**Comment by akdenme** [comment]
tq, its fixed.. 
but when im testing it in ios browser.. and clicking the arrow it scroll up and cannot scroll down..

**Comment by annapogorelova** [comment]
@akdenme , I've spotted a potential bug and attempted to fix it in **v.2.0.7** which I've just published. Unfortunately, I can't test it on iOS browser because I don't own the iOS device. So, please, test it now.

**Comment by akdenme** [comment]
already tried it.. but still the same.. 
in ios browser still after click the arrow it scroll up and cannot scroll down.. 
but in android it works perfectly... sorry for being such a burden...

**Comment by annapogorelova** [comment]
@akdenme , if the animation is not important to you, you can set `animate="false"` when Safari browser is detected, then it will scroll top just by calling `window.scrollTo(0, 0);` without the usage of `setInterval` (that is most likely causing the problem on Safari Mobile). Meanwhile, I'll do more investigation into this issue.
